/**:
  ros__parameters:
    wheel_radius: 0.279 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.155 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.5 # between front wheel center and rear wheel center
    wheel_tread: 1.377 # between left wheel center and right wheel center
    front_overhang: 0.495 # between front wheel center and vehicle front
    rear_overhang: 0.45 # between rear wheel center and vehicle rear
    left_overhang: 0.328 # between left wheel center and vehicle left
    right_overhang: 0.328 # between right wheel center and vehicle right
    vehicle_height: 1.673
    max_steer_angle: 0.633 # [rad]
